"use client";
import Link from "next/link";
import Image from "next/image";
import {useEffect,useState} from "react";
import {adminRequest,ApiError} from "../../lib/admin-api";
import {Product,Media,money} from "../../lib/product";
const blank=():Product=>({slug:"",name:"",price:599,originalPrice:900,description:"",details:"",composition:"100% Cotton",gsm:240,collections:["women"],colours:["Black"],sizes:["S","M","L","XL"],media:[],newIn:true,sortOrder:100,collectionOrder:100,status:"DRAFT"});
export default function AdminPortal(){
 const [user,setUser]=useState<string|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[products,setProducts]=useState<Product[]>([]),[draft,setDraft]=useState<Product|null>(null),[error,setError]=useState(""),[notice,setNotice]=useState(""),[query,setQuery]=useState("");
 useEffect(()=>{if(!notice||error)return;const timer=setTimeout(()=>setNotice(""),6000);return()=>clearTimeout(timer);},[notice,error]);
 async function refresh(){setProducts(await adminRequest<Product[]>("/api/admin/products"));}
 useEffect(()=>{let live=true;adminRequest<{username:string}>("/api/auth/me").then(async me=>{const list=await adminRequest<Product[]>("/api/admin/products");if(live){setUser(me.username);setProducts(list);}}).catch(e=>{if(live&&(!(e instanceof ApiError)||e.status!==401))setError("Cannot connect to admin service. Start the backend and reload.");}).finally(()=>{if(live)setLoading(false);});return()=>{live=false;};},[]);
 function change<K extends keyof Product>(key:K,value:Product[K]){setDraft(d=>d?{...d,[key]:value}:d);}
 function photo(i:number,patch:Partial<Media>){if(draft)change("media",draft.media.map((m,j)=>i===j?{...m,...patch}:m));}
 async function login(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const f=new FormData(e.currentTarget);try{await adminRequest("/api/auth/login",{method:"POST",body:new URLSearchParams({username:String(f.get("username")),password:String(f.get("password"))})});setUser((await adminRequest<{username:string}>("/api/auth/me")).username);await refresh();}catch(e){setError(e instanceof ApiError&&e.status===401?"Incorrect username or password.":e instanceof ApiError&&e.status===429?"Too many attempts. Try again in 15 minutes.":"Cannot sign in. Check your backend connection.");}finally{setBusy(false);}}
 async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!draft)return;setBusy(true);setError("");setNotice("");try{const p=await adminRequest<Product>(draft.id?`/api/admin/products/${draft.id}`:"/api/admin/products",{method:draft.id?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(draft)});setDraft(p);await refresh();setNotice(p.status==="PUBLISHED"?"Saved and published. Check this product on the storefront.":p.status==="ARCHIVED"?"Archived and hidden from the storefront.":"Draft saved and hidden from the storefront.");}catch(e){if(e instanceof ApiError&&(e.status===401||e.status===403)){setUser(null);setDraft(null);setError("Your session expired. Sign in again.");}else setError(e instanceof Error?e.message:"Could not save product");}finally{setBusy(false);}}
 async function upload(files:FileList|null){if(!files||!files.length||!draft)return;setBusy(true);setError("");setNotice("");const added:Media[]=[];try{for(const file of Array.from(files)){const form=new FormData();form.append("file",file);const result=await adminRequest<{url:string}>("/api/admin/media",{method:"POST",body:form});added.push({url:result.url,alt:draft.name||file.name,colour:draft.colours[0],kind:"image",contain:false});}setNotice(`${added.length} photo${added.length===1?"":"s"} uploaded. Save the product to apply changes.`);}catch(e){setError(e instanceof Error?e.message:"Upload failed");}finally{setDraft(d=>d?{...d,media:[...d.media,...added]}:d);setBusy(false);}}
 async function logout(){setBusy(true);try{await adminRequest("/api/auth/logout",{method:"POST"});setUser(null);setDraft(null);setProducts([]);}catch{setError("Could not sign out. Try again.");}finally{setBusy(false);}}
 function reorder(i:number,step:number){if(!draft)return;const list=[...draft.media];[list[i],list[i+step]]=[list[i+step],list[i]];change("media",list);}
 if(loading)return <main className="admin-page"><p>Connecting to admin…</p></main>;
 return <main className="admin-page"><header className="admin-header"><Link className="brand-logo" href="/" aria-label="Styled Somehow home"><span>STYLED</span><span>SOMEHOW</span></Link><h1>Admin · Products</h1><Link href="/admin/inventory">Manage stock →</Link>{user&&<button disabled={busy} onClick={logout}>Sign out</button>}</header>{(error||notice)&&<div className={`admin-toast ${error?"admin-toast--error":"admin-toast--success"}`} role={error?"alert":"status"} aria-atomic="true"><p>{error||notice}</p><button type="button" aria-label="Dismiss notification" onClick={()=>{setError("");setNotice("");}}>×</button></div>}
 {!user?<form className="admin-login" onSubmit={login}><h2>Owner sign in</h2><label>Username<input name="username" autoComplete="username" required/></label><label>Password<input name="password" type="password" autoComplete="current-password" required/></label><button disabled={busy}>{busy?"Signing in…":"Sign in"}</button></form>:<div className="admin-layout"><aside className="admin-catalog"><div className="admin-toolbar"><h2>Catalogue ({products.length})</h2><button disabled={busy} onClick={()=>{setDraft(blank());setNotice("");setError("");}}>Add product</button></div><label>Find a product<input type="search" value={query} onChange={e=>setQuery(e.target.value)}/></label><button disabled={busy} onClick={()=>refresh().catch(()=>setError("Could not refresh catalogue"))}>Refresh catalogue</button><div className="admin-product-list">{products.filter(p=>`${p.name} ${p.slug}`.toLowerCase().includes(query.toLowerCase())).map(p=><button key={p.id} disabled={busy} className={p.id===draft?.id?"is-selected":""} onClick={()=>{setDraft(structuredClone(p));setError("");setNotice("");}}><span className="admin-product-thumb">{p.media.find(m=>m.kind==="image")?<Image src={p.media.find(m=>m.kind==="image")!.url} alt="" width={56} height={72} unoptimized={p.media.find(m=>m.kind==="image")!.url.startsWith("/api/")} />:<span aria-hidden="true">No photo</span>}</span><span className="admin-product-summary"><strong>{p.name}</strong><span>{p.status} · {money(p.price)}</span></span></button>)}</div></aside>
 {draft?<form className="admin-editor" onSubmit={save}><fieldset disabled={busy}><h2>{draft.id?"Edit product":"Add product"}</h2><p>Save a draft first, then publish when photos and details are ready.</p><div className="admin-fields"><label>Product name<input required maxLength={180} value={draft.name} onChange={e=>change("name",e.target.value)}/></label><label>Product URL<input required pattern="[a-z0-9]+(-[a-z0-9]+)*" maxLength={100} readOnly={!!draft.id} value={draft.slug} placeholder="your-design-oversized-t-shirt" onChange={e=>change("slug",e.target.value)}/><small>Saved product URLs stay fixed.</small></label><label>Selling price (₹)<input type="number" required min={1} max={1000000} value={draft.price} onChange={e=>change("price",Number(e.target.value))}/></label><label>Original price (₹)<input type="number" required min={draft.price} max={1000000} value={draft.originalPrice} onChange={e=>change("originalPrice",Number(e.target.value))}/></label><label>Status<select value={draft.status} onChange={e=>change("status",e.target.value as Product["status"])}><option>DRAFT</option><option>PUBLISHED</option><option>ARCHIVED</option></select></label><label>New In order<input type="number" required min={0} value={draft.sortOrder} onChange={e=>change("sortOrder",Number(e.target.value))}/><small>Lower numbers appear first.</small></label></div>
 <label>Collection order<input type="number" required min={0} value={draft.collectionOrder} onChange={e=>change("collectionOrder",Number(e.target.value))}/><small>Lower numbers appear first in Men/Women.</small></label><label>Short description<textarea required maxLength={2000} value={draft.description} onChange={e=>change("description",e.target.value)}/></label><label>Product details<textarea required maxLength={4000} value={draft.details} onChange={e=>change("details",e.target.value)}/></label><div className="admin-fields"><label>Composition<input required maxLength={100} value={draft.composition} onChange={e=>change("composition",e.target.value)}/></label><label>GSM<input type="number" required min={1} max={1000} value={draft.gsm} onChange={e=>change("gsm",Number(e.target.value))}/></label></div>
 <div className="admin-checks"><span>Collections</span>{["women","men"].map(c=><label key={c}><input type="checkbox" checked={draft.collections.includes(c)} onChange={e=>change("collections",e.target.checked?[...draft.collections,c]:draft.collections.filter(x=>x!==c))}/>{c}</label>)}<label><input type="checkbox" checked={draft.newIn} onChange={e=>change("newIn",e.target.checked)}/>Show in New In</label></div><div className="admin-checks"><span>Sizes</span>{["S","M","L","XL"].map(s=><label key={s}><input type="checkbox" checked={draft.sizes.includes(s)} onChange={e=>change("sizes",e.target.checked?[...draft.sizes,s]:draft.sizes.filter(x=>x!==s))}/>{s}</label>)}</div><label>Colours (one per line)<textarea required value={draft.colours.join("\n")} onChange={e=>change("colours",e.target.value.split("\n"))} onBlur={()=>change("colours",Array.from(new Set(draft.colours.map(c=>c.trim()).filter(Boolean))))}/></label>
 <h3>Photos</h3><p>The first photo is the listing image. Assign a photo to every colour. Use the arrows to reorder.</p><label>Upload JPEG, PNG or WebP photos · up to 8 MB each<input type="file" multiple accept="image/jpeg,image/png,image/webp" onChange={e=>{void upload(e.target.files);e.target.value="";}}/></label><div className="admin-media">{draft.media.map((m,i)=><article key={`${m.url}-${i}`}><div className="admin-media-preview">{m.kind==="video"?<video src={m.url} controls/>:// eslint-disable-next-line @next/next/no-img-element
 <img src={m.url} alt={m.alt}/>}</div><strong>{i===0?"Listing image":`Photo ${i+1}`}</strong><label>Photo description<input required maxLength={240} value={m.alt} onChange={e=>photo(i,{alt:e.target.value})}/></label><label>Colour<select value={m.colour} onChange={e=>photo(i,{colour:e.target.value})}>{!draft.colours.includes(m.colour)&&<option value={m.colour}>{m.colour} — choose a current colour</option>}{draft.colours.map((c,j)=><option key={`${c}-${j}`}>{c}</option>)}</select></label><label className="admin-checks"><input type="checkbox" checked={m.contain} onChange={e=>photo(i,{contain:e.target.checked})}/>Show complete artwork</label><div className="admin-toolbar"><button type="button" disabled={i===0} aria-label={`Move photo ${i+1} earlier`} onClick={()=>reorder(i,-1)}>↑</button><button type="button" disabled={i===draft.media.length-1} aria-label={`Move photo ${i+1} later`} onClick={()=>reorder(i,1)}>↓</button><button type="button" onClick={()=>change("media",draft.media.filter((_,j)=>j!==i))}>Remove</button></div></article>)}</div><div className="admin-actions"><button type="submit">{busy?"Saving…":`Save ${draft.status.toLowerCase()}`}</button>{draft.id&&draft.status==="PUBLISHED"&&<Link target="_blank" href={`/products/${draft.slug}`}>View product ↗</Link>}<Link target="_blank" href="/">Open storefront ↗</Link></div></fieldset></form>:<section className="admin-editor"><h2>Your product workspace</h2><p>Select a product or add a new design.</p><p>Inventory, orders and automatic shipping will be added in later steps.</p></section>}</div>}</main>;
}
