"use client";
import Link from "next/link";
import {useEffect,useRef,useState} from "react";
import {adminRequest} from "../../../lib/admin-api";
type Stock={id:number;version:number;colour:string;size:string;quantity:number;lowStockThreshold:number};
type Movement={id:number;colour:string;size:string;delta:number;resultingQuantity:number;reason:string;actor:string;occurredAt:string};
export default function InventoryPortal(){
 const [stocks,setStocks]=useState<Stock[]>([]),[history,setHistory]=useState<Movement[]>([]),[selected,setSelected]=useState<Stock|null>(null),[delta,setDelta]=useState(""),[reason,setReason]=useState(""),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true);
 const pending=useRef<{signature:string;key:string}|null>(null);
 async function refresh(){const [s,h]=await Promise.all([adminRequest<Stock[]>("/api/admin/inventory"),adminRequest<Movement[]>("/api/admin/inventory/movements")]);setStocks(s);setHistory(h);}
 useEffect(()=>{let live=true;Promise.all([adminRequest<Stock[]>("/api/admin/inventory"),adminRequest<Movement[]>("/api/admin/inventory/movements")]).then(([s,h])=>{if(live){setStocks(s);setHistory(h);}}).catch(()=>{if(live)setError("Cannot load inventory. Sign in through Products and retry.");}).finally(()=>{if(live)setLoading(false);});return()=>{live=false;};},[]);
 useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(""),6000);return()=>clearTimeout(timer);},[notice]);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!selected)return;const signature=JSON.stringify([selected.id,selected.version,Number(delta),reason.trim()]);if(pending.current?.signature!==signature)pending.current={signature,key:crypto.randomUUID()};setBusy(true);setError("");setNotice("");try{await adminRequest(`/api/admin/inventory/${selected.id}/adjustments`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({version:selected.version,delta:Number(delta),reason:reason.trim(),requestId:pending.current.key})});pending.current=null;setSelected(null);setDelta("");setReason("");await refresh();setNotice("Stock adjustment saved across all designs using this colour and size.");}catch(e){setError(e instanceof Error?e.message:"Could not adjust stock");}finally{setBusy(false);}}
 return <main className="admin-page"><header className="admin-header"><Link href="/admin">← Products / sign in</Link><h1>Blank T-shirt inventory</h1><button disabled={busy} onClick={()=>refresh().catch(()=>setError("Refresh failed"))}>Refresh</button></header>{(error||notice)&&<div className={`admin-toast ${error?"admin-toast--error":"admin-toast--success"}`} role={error?"alert":"status"}><p>{error||notice}</p><button aria-label="Dismiss notification" onClick={()=>{setError("");setNotice("");}}>×</button></div>}
 <section className="admin-editor"><h2>Shared oversized blanks · {stocks.reduce((n,s)=>n+s.quantity,0)} available</h2><p>Every design uses the same blank garment type. Stock is shared by colour and size. Low stock means 3 or fewer blanks.</p>{loading?<p>Loading…</p>:<div className="inventory-table-wrap"><table className="inventory-table"><thead><tr><th>Colour</th><th>Size</th><th>Quantity</th><th>Status</th><th>Action</th></tr></thead><tbody>{stocks.map(s=><tr key={s.id}><td>{s.colour}</td><td>{s.size}</td><td>{s.quantity}</td><td>{s.quantity===0?"Out of stock":s.quantity<=s.lowStockThreshold?"Low stock":"In stock"}</td><td><button disabled={busy} onClick={()=>{setSelected(s);setDelta("");setReason("");}}>Adjust</button></td></tr>)}</tbody></table></div>}</section>
 {selected&&<form className="admin-editor inventory-adjust" onSubmit={submit}><h2>Adjust {selected.colour} · {selected.size}</h2><p>Current quantity: {selected.quantity}. Enter a positive number for restock or a negative number for damage/removal.</p><fieldset disabled={busy}><label>Quantity change<input autoFocus type="number" required min={-selected.quantity} max={100000} step={1} value={delta} onChange={e=>setDelta(e.target.value)}/></label><label>Reason<textarea required maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></label><p>Result: {selected.quantity+Number(delta)} blanks</p><div className="admin-actions"><button disabled={!Number(delta)||!reason.trim()}>Save adjustment</button><button type="button" onClick={()=>setSelected(null)}>Cancel</button></div></fieldset></form>}
 <section className="admin-editor inventory-history"><h2>Recent stock changes</h2><p>Latest 100 entries. Opening quantities are imported once; restarting does not reset stock.</p><div className="inventory-table-wrap"><table className="inventory-table"><thead><tr><th>When</th><th>Blank</th><th>Change</th><th>Balance</th><th>Reason</th><th>By</th></tr></thead><tbody>{history.map(m=><tr key={m.id}><td>{new Date(m.occurredAt).toLocaleString()}</td><td>{m.colour} · {m.size}</td><td>{m.delta>0?"+":""}{m.delta}</td><td>{m.resultingQuantity}</td><td>{m.reason}</td><td>{m.actor}</td></tr>)}</tbody></table></div></section></main>;
}
