CREATE TABLE products (id BIGINT AUTO_INCREMENT PRIMARY KEY, version BIGINT NOT NULL DEFAULT 0, slug VARCHAR(100) NOT NULL UNIQUE, name VARCHAR(255) NOT NULL, price INT NOT NULL, original_price INT NOT NULL, description VARCHAR(2000), details VARCHAR(4000), composition VARCHAR(255), gsm INT NOT NULL, new_in BOOLEAN NOT NULL, sort_order INT NOT NULL, collection_order INT NOT NULL DEFAULT 0, status VARCHAR(255));
CREATE TABLE product_collections (product_id BIGINT NOT NULL, position INT NOT NULL, value VARCHAR(255), PRIMARY KEY(product_id,position), FOREIGN KEY(product_id) REFERENCES products(id));
CREATE TABLE product_colours (product_id BIGINT NOT NULL, position INT NOT NULL, value VARCHAR(255), PRIMARY KEY(product_id,position), FOREIGN KEY(product_id) REFERENCES products(id));
CREATE TABLE product_sizes (product_id BIGINT NOT NULL, position INT NOT NULL, value VARCHAR(255), PRIMARY KEY(product_id,position), FOREIGN KEY(product_id) REFERENCES products(id));
CREATE TABLE product_media (product_id BIGINT NOT NULL, position INT NOT NULL, url VARCHAR(255), alt VARCHAR(255), colour VARCHAR(255), kind VARCHAR(255), contain_image BOOLEAN NOT NULL, PRIMARY KEY(product_id,position), FOREIGN KEY(product_id) REFERENCES products(id));
INSERT INTO products (id,slug,name,price,original_price,description,details,composition,gsm,new_in,sort_order,status) VALUES (1,'cherry-zest-oversized-t-shirt','Cherry Zest Oversized T-Shirt',599,999,'A little sweet, a little tangy. Cherry-and-citrus artwork on a white oversized tee.','White oversized T-shirt with a cherry-and-citrus front graphic, pink and red stripes, and a stamp-style border. 240 GSM, 100% cotton fabric.','100% Cotton',240,true,0,'PUBLISHED');
INSERT INTO product_collections VALUES (1,0,'women');
INSERT INTO product_colours VALUES (1,0,'White');
INSERT INTO product_sizes VALUES (1,0,'S');
INSERT INTO product_sizes VALUES (1,1,'M');
INSERT INTO product_sizes VALUES (1,2,'L');
INSERT INTO product_sizes VALUES (1,3,'XL');
INSERT INTO product_media VALUES (1,0,'/images/cherry-zest-1.webp','Cherry Zest Oversized T-Shirt','White','image',false);
INSERT INTO product_media VALUES (1,1,'/images/cherry-zest-2.webp','Cherry Zest Oversized T-Shirt','White','image',false);
INSERT INTO product_media VALUES (1,2,'/images/cherry-zest-detail.webp','Cherry Zest Oversized T-Shirt','White','image',true);
INSERT INTO products (id,slug,name,price,original_price,description,details,composition,gsm,new_in,sort_order,status) VALUES (2,'untamed-torque-oversized-t-shirt','Untamed Torque Oversized T-Shirt',999,1200,'Built for the untamed. A split-car graphic across the front and back of a white oversized tee.','White oversized T-shirt with Untamed chest lettering and a split-car graphic spanning the front and back. 240 GSM, 100% cotton fabric.','100% Cotton',240,true,1,'PUBLISHED');
INSERT INTO product_collections VALUES (2,0,'men');
INSERT INTO product_colours VALUES (2,0,'White');
INSERT INTO product_sizes VALUES (2,0,'S');
INSERT INTO product_sizes VALUES (2,1,'M');
INSERT INTO product_sizes VALUES (2,2,'L');
INSERT INTO product_sizes VALUES (2,3,'XL');
INSERT INTO product_media VALUES (2,0,'/images/untamed-torque-front.webp','Untamed Torque Oversized T-Shirt','White','image',false);
INSERT INTO product_media VALUES (2,1,'/images/untamed-torque-back.webp','Untamed Torque Oversized T-Shirt','White','image',false);
INSERT INTO product_media VALUES (2,2,'/images/untamed-torque-detail.webp','Untamed Torque Oversized T-Shirt','White','image',true);
INSERT INTO products (id,slug,name,price,original_price,description,details,composition,gsm,new_in,sort_order,status) VALUES (3,'shes-winning-oversized-t-shirt','She’s Winning Oversized T-Shirt',599,900,'She can. She will. She did. Pink statement lettering on a black oversized tee.','Black oversized T-shirt with pink gradient SHE lettering and the words She Can, She Will, She Did — She’s Winning. 240 GSM, 100% cotton fabric.','100% Cotton',240,true,2,'PUBLISHED');
INSERT INTO product_collections VALUES (3,0,'women');
INSERT INTO product_colours VALUES (3,0,'Black');
INSERT INTO product_sizes VALUES (3,0,'S');
INSERT INTO product_sizes VALUES (3,1,'M');
INSERT INTO product_sizes VALUES (3,2,'L');
INSERT INTO product_sizes VALUES (3,3,'XL');
INSERT INTO product_media VALUES (3,0,'/images/shes-winning-1.webp','She’s Winning Oversized T-Shirt','Black','image',false);
INSERT INTO product_media VALUES (3,1,'/images/shes-winning-2.webp','She’s Winning Oversized T-Shirt','Black','image',false);
INSERT INTO product_media VALUES (3,2,'/images/shes-winning-detail.webp','She’s Winning Oversized T-Shirt','Black','image',true);
INSERT INTO products (id,slug,name,price,original_price,description,details,composition,gsm,new_in,sort_order,status) VALUES (4,'chilli-crush-oversized-t-shirt','Chilli Crush Oversized T-Shirt',699,900,'Bring the heat. Red chillies on a pink canvas give this black oversized tee a bold, playful edge.','Black oversized T-shirt with red chilli artwork on an irregular pink canvas. Dropped shoulders and short sleeves. 240 GSM, 100% cotton fabric.','100% Cotton',240,true,3,'PUBLISHED');
INSERT INTO product_collections VALUES (4,0,'women');
INSERT INTO product_colours VALUES (4,0,'Black');
INSERT INTO product_sizes VALUES (4,0,'S');
INSERT INTO product_sizes VALUES (4,1,'M');
INSERT INTO product_sizes VALUES (4,2,'L');
INSERT INTO product_sizes VALUES (4,3,'XL');
INSERT INTO product_media VALUES (4,0,'/images/chilli-crush-1.webp','Chilli Crush Oversized T-Shirt','Black','image',false);
INSERT INTO product_media VALUES (4,1,'/images/chilli-crush-2.webp','Chilli Crush Oversized T-Shirt','Black','image',false);
INSERT INTO product_media VALUES (4,2,'/images/chilli-crush-detail.webp','Chilli Crush Oversized T-Shirt','Black','image',true);
INSERT INTO products (id,slug,name,price,original_price,description,details,composition,gsm,new_in,sort_order,status) VALUES (5,'bitchari-oversized-t-shirt','Bitchआरी Oversized T-Shirt',599,900,'A little wordplay, a lot of attitude. Bold yellow Bitchआरी lettering with pink shadowing on a black oversized tee.','Black oversized T-shirt with yellow Bitchआरी lettering and pink shadow detailing. Dropped shoulders and short sleeves. 240 GSM, 100% cotton fabric.','100% Cotton',240,true,4,'PUBLISHED');
INSERT INTO product_collections VALUES (5,0,'women');
INSERT INTO product_colours VALUES (5,0,'Black');
INSERT INTO product_sizes VALUES (5,0,'S');
INSERT INTO product_sizes VALUES (5,1,'M');
INSERT INTO product_sizes VALUES (5,2,'L');
INSERT INTO product_sizes VALUES (5,3,'XL');
INSERT INTO product_media VALUES (5,0,'/images/bitchari-1.webp','Bitchआरी Oversized T-Shirt','Black','image',false);
INSERT INTO product_media VALUES (5,1,'/images/bitchari-2.webp','Bitchआरी Oversized T-Shirt','Black','image',false);
INSERT INTO product_media VALUES (5,2,'/images/bitchari-3.webp','Bitchआरी Oversized T-Shirt','Black','image',false);
INSERT INTO product_media VALUES (5,3,'/images/bitchari-4.webp','Bitchआरी Oversized T-Shirt','Black','image',true);
INSERT INTO products (id,slug,name,price,original_price,description,details,composition,gsm,new_in,sort_order,status) VALUES (6,'sabr-oversized-t-shirt','Sabr Oversized T-Shirt',499,600,'Wear your calm. Minimal सब्र lettering meets a relaxed oversized silhouette, available in Black and White.','Oversized T-shirt with सब्र chest lettering, dropped shoulders and short sleeves. Available in Black and White. 240 GSM, 100% cotton fabric.','100% Cotton',240,false,5,'PUBLISHED');
INSERT INTO product_collections VALUES (6,0,'men');
INSERT INTO product_colours VALUES (6,0,'Black');
INSERT INTO product_colours VALUES (6,1,'White');
INSERT INTO product_sizes VALUES (6,0,'S');
INSERT INTO product_sizes VALUES (6,1,'M');
INSERT INTO product_sizes VALUES (6,2,'L');
INSERT INTO product_sizes VALUES (6,3,'XL');
INSERT INTO product_media VALUES (6,0,'/images/sabr-black.webp','Sabr Oversized T-Shirt','Black','image',false);
INSERT INTO product_media VALUES (6,1,'/images/sabr-black-seated.webp','Sabr Oversized T-Shirt','Black','image',false);
INSERT INTO product_media VALUES (6,2,'/images/sabr-white.webp','Sabr Oversized T-Shirt','White','image',false);
INSERT INTO product_media VALUES (6,3,'/videos/sabr-white.mp4','Sabr White in motion','White','video',true);

UPDATE products SET collection_order=1 WHERE slug='cherry-zest-oversized-t-shirt';
UPDATE products SET collection_order=2 WHERE slug='shes-winning-oversized-t-shirt';
UPDATE products SET collection_order=3 WHERE slug='bitchari-oversized-t-shirt';
UPDATE products SET collection_order=1 WHERE slug='sabr-oversized-t-shirt';
