"use client";
import {useEffect,useState} from "react";
import {adminRequest} from "../../../lib/admin-api";
import {PendingOrder} from "../../../lib/cart";
import {StatusBadge,ModeBadge,shortRef,dateLabel} from "./badges";
type Receipt={id:string;orderId:string;amount:number;status:string;refundId?:string;reason:string;retries:number;createdAt:string};
export default function Payments({orders}:{orders:PendingOrder[]}){
 const [rows,setRows]=useState<Receipt[]>([]),[error,setError]=useState(""),[loading,setLoading]=useState(true),[search,setSearch]=useState("");
 useEffect(()=>{let live=true;async function load(){try{const data=await adminRequest<Receipt[]>("/api/admin/payments");if(live){setRows(data);setError("");}}catch(e){if(live)setError(e instanceof Error?e.message:"Cannot load payments");}finally{if(live)setLoading(false);}}void load();const timer=setInterval(()=>void load(),30000);return()=>{live=false;clearInterval(timer);};},[]);
 const filtered=rows.filter(r=>[r.id,r.orderId,r.refundId||"",r.status].join(" ").toLowerCase().includes(search.trim().toLowerCase()));
 return <section className="ops-section"><div className="ops-section-heading"><div><h2>Payments & refunds</h2><p>Latest 100 records · Status refreshes every 30 seconds.</p></div></div><label className="ops-payment-search">Find payment<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Payment, order, refund reference or status"/></label>{error&&<p className="admin-error" role="alert">{error}</p>}{loading?<p className="ops-empty">Loading payments…</p>:!filtered.length?<p className="ops-empty">{rows.length?"No payments match your search.":"No verified payments recorded yet."}</p>:<div className="ops-table-wrap" role="region" aria-label="Payments table, scroll horizontally on small screens" tabIndex={0}><table className="ops-table"><thead><tr><th scope="col">Payment / order</th><th scope="col">Mode</th><th scope="col">Amount</th><th scope="col">Status</th><th scope="col">Refund</th><th scope="col">Retries</th><th scope="col">Notes / references</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td><strong className="ops-ref">{r.id}</strong><small>Order #{shortRef(r.orderId)}</small><small>{dateLabel(r.createdAt)}</small></td><td><ModeBadge mode={orders.find(o=>o.id===r.orderId)?.paymentMode}/></td><td><strong>₹{(r.amount/100).toFixed(2)}</strong></td><td><StatusBadge status={r.status}/></td><td className="ops-ref">{r.refundId||"—"}</td><td><span className={r.retries?"ops-retry-count":""}>{r.retries}</span></td><td><details className="ops-payment-notes"><summary>View notes</summary><p>{r.reason}</p><dl><dt>Full order reference</dt><dd className="ops-ref">{r.orderId}</dd></dl>{r.status==="REVIEW_REQUIRED"&&<p className="ops-review-note">Review in Razorpay before fulfillment. Record stock corrections through Inventory.</p>}</details></td></tr>)}</tbody></table></div>}</section>;
}
