/* eslint-disable @next/next/no-img-element */
"use client";
import Link from "next/link";
import Payments from "./payments";
import OrderDetails from "./order-details";
import {StatusBadge,ModeBadge,shortRef,dateLabel} from "./badges";
import {Fragment,useEffect,useState} from "react";
import {PendingOrder} from "../../../lib/cart";
import {adminRequest} from "../../../lib/admin-api";
import {money} from "../../../lib/product";
export default function OrdersView(){
 const [orders,setOrders]=useState<PendingOrder[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[tab,setTab]=useState("orders"),[search,setSearch]=useState(""),[status,setStatus]=useState("ALL"),[mode,setMode]=useState("ALL"),[selected,setSelected]=useState<string|null>(null);
 useEffect(()=>{let live=true;adminRequest<PendingOrder[]>("/api/admin/orders").then(data=>{if(live)setOrders(data);}).catch(e=>{if(live)setError(e instanceof Error?e.message:"Cannot load orders");}).finally(()=>{if(live)setLoading(false);});return()=>{live=false;};},[]);
 const query=search.trim().toLowerCase();
 const filtered=orders.filter(o=>(status==="ALL"||o.status===status)&&(mode==="ALL"||o.paymentMode===mode||mode==="UNASSIGNED"&&!o.paymentMode)&&(!query||[o.id,o.name,o.email,o.phone,...o.items.map(i=>i.name)].join(" ").toLowerCase().includes(query)));
 return <main className="admin-page ops-page"><header className="admin-header"><div><p className="ops-eyebrow">STORE ADMIN</p><h1>Orders & payments</h1><p className="ops-subtitle">Review customers, payment status and refunds in one place.</p></div><nav className="ops-nav" aria-label="Admin navigation"><Link href="/admin">Products / sign in</Link><Link href="/admin/inventory">Inventory</Link></nav></header>
 <div className="ops-test-banner"><ModeBadge mode="TEST"/><p><strong>Test orders are not for dispatch.</strong> Test payments reduce development inventory. Restore stock through Inventory after testing.</p></div>
 <div className="ops-stats">{[{label:"Recent orders",value:orders.length,tone:"neutral"},{label:"Paid",value:orders.filter(o=>o.status==="PAID").length,tone:"success"},{label:"Awaiting payment",value:orders.filter(o=>o.status==="PENDING_PAYMENT").length,tone:"warning"},{label:"Refunds / review",value:orders.filter(o=>o.status.startsWith("REFUND")&&o.status!=="REFUNDED"||o.status==="PAYMENT_REVIEW").length,tone:"danger"}].map(s=><div className={`ops-stat ops-stat--${s.tone}`} key={s.label}><span>{s.label}</span><strong>{loading?"—":s.value}</strong></div>)}</div>
 <div className="ops-tabs" aria-label="Order views"><button aria-pressed={tab==="orders"} onClick={()=>setTab("orders")}>Orders</button><button aria-pressed={tab==="payments"} onClick={()=>setTab("payments")}>Payments & refunds</button></div>
 {error&&<p className="admin-error" role="alert">{error}</p>}
 {tab==="payments"?<Payments orders={orders}/>:<section className="ops-section"><div className="ops-section-heading"><div><h2>Order listing</h2><p>Showing {filtered.length} of {orders.length} recent orders. Open details for the full reference and address.</p></div><button onClick={()=>window.location.reload()} disabled={loading}>Refresh</button></div>
 <div className="ops-filters"><label>Search<input type="search" placeholder="Order, customer, email or product" value={search} onChange={e=>setSearch(e.target.value)}/></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="ALL">All statuses</option>{[...new Set(orders.map(o=>o.status))].map(s=><option key={s} value={s}>{s.replaceAll("_"," ")}</option>)}</select></label><label>Payment mode<select value={mode} onChange={e=>setMode(e.target.value)}><option value="ALL">All modes</option><option value="TEST">Test</option><option value="LIVE">Live</option><option value="UNASSIGNED">Not assigned</option></select></label></div>
 {loading?<p className="ops-empty">Loading orders…</p>:!filtered.length?<p className="ops-empty">{orders.length?"No orders match these filters.":"No orders yet."}</p>:<div className="ops-table-wrap" role="region" aria-label="Orders table, scroll horizontally on small screens" tabIndex={0}><table className="ops-table"><thead><tr><th scope="col">Order / date</th><th scope="col">Customer</th><th scope="col">Products</th><th scope="col">Total</th><th scope="col">Status</th><th scope="col">Mode</th><th scope="col">Details</th></tr></thead><tbody>{filtered.map(o=><Fragment key={o.id}><tr className={selected===o.id?"ops-row-selected":""}><td><strong className="ops-ref">#{shortRef(o.id)}</strong><small>{dateLabel(o.createdAt)}</small></td><td><strong>{o.name}</strong><small>{o.email}</small><small>{o.phone}</small></td><td><div className="ops-product">{o.items[0]?.image&&<img src={o.items[0].image} alt="" loading="lazy"/>}<div>{o.items.map((i,j)=><div key={j}><strong>{i.name}</strong><small>{i.colour} / {i.size} · Qty {i.quantity}</small></div>)}</div></div></td><td><strong>{money(o.total)}</strong><small>Free shipping</small></td><td><StatusBadge status={o.status}/></td><td><ModeBadge mode={o.paymentMode}/></td><td><button className="ops-detail-button" aria-expanded={selected===o.id} aria-controls={`order-details-${o.id}`} onClick={()=>setSelected(selected===o.id?null:o.id)}>{selected===o.id?"Close":"View details"}</button></td></tr>{selected===o.id&&<tr className="ops-expanded-row"><td colSpan={7}><OrderDetails order={o} onClose={()=>setSelected(null)}/></td></tr>}</Fragment>)}</tbody></table></div>}

 </section>}</main>;
}
