"use client";
import Link from "next/link";
import Image from "next/image";
import {useEffect,useState} from "react";
import {CartItem,Quote,readCart,writeCart,checkoutItems} from "../../lib/cart";
import {adminRequest} from "../../lib/admin-api";
import {Product,money} from "../../lib/product";
export default function CartView(){
 const [items,setItems]=useState<CartItem[]|null>(null),[products,setProducts]=useState<Product[]>([]),[quote,setQuote]=useState<Quote|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
 useEffect(()=>{let live=true;fetch("/api/products",{cache:"no-store"}).then(r=>{if(!r.ok)throw new Error("Catalogue unavailable");return r.json();}).then((p:Product[])=>{if(live){setProducts(p);const cart=readCart().map(i=>({...i,colour:i.colour||p.find(v=>v.slug===i.slug)?.colours[0]||""}));writeCart(cart);setItems(cart);}}).catch(()=>{if(live){setItems(readCart());setError("Cannot load product details. Please retry shortly.");}});return()=>{live=false;};},[]);
 useEffect(()=>{if(!items||!items.length)return;let live=true;adminRequest<Quote>("/api/cart/quote",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({items:checkoutItems(items)})}).then(q=>{if(live){setQuote(q);setError("");}}).catch(e=>{if(live){setQuote(null);setError(e instanceof Error?e.message:"Could not validate cart");}}).finally(()=>{if(live)setBusy(false);});return()=>{live=false;};},[items]);
 function change(next:CartItem[]){try{writeCart(next);setItems(next);setQuote(null);setBusy(next.length>0);setError("");}catch{setError("Cannot save your cart in this browser.");}}
 return <main className="shopping-page"><nav className="product-nav"><Link className="brand-logo" href="/" aria-label="Styled Somehow home"><span>STYLED</span><span>SOMEHOW</span></Link><Link href="/#new-in">← Continue shopping</Link></nav><h1>Your cart</h1>{error&&<p className="shopping-error" role="alert">{error}</p>}
 {!items?<p>Loading cart…</p>:!items.length?<p>Your cart is empty. <Link href="/#new-in">Explore the collection</Link>.</p>:<div className="shopping-layout"><section>{items.map((item,index)=>{const p=products.find(p=>p.slug===item.slug),image=p?.media.find(m=>m.colour===item.colour&&m.kind==="image");return <article className="cart-row" key={`${item.slug}-${item.colour}-${item.size}-${index}`}>
 {image&&<Image src={image.url} alt={image.alt} width={100} height={130} unoptimized={image.url.startsWith("/api/")}/>}<div><Link href={`/products/${item.slug}`}>{p?.name||item.name||item.slug}</Link><p>{item.colour||"Select colour again"} · {item.size}</p>{p&&<p>{money(p.price)} each</p>}<label>Quantity<input type="number" min={1} max={20} value={item.quantity} onChange={e=>{const quantity=Number(e.target.value);if(Number.isInteger(quantity)&&quantity>=1&&quantity<=20)change(items.map((i,j)=>j===index?{...i,quantity}:i));}}/></label><button type="button" onClick={()=>change(items.filter((_,j)=>j!==index))}>Remove</button></div></article>;})}</section><aside className="checkout-summary"><h2>Order summary</h2>{quote?<><p>Subtotal <strong>{money(quote.subtotal)}</strong></p><p>Shipping <strong>Free · ₹0</strong></p><p>Total <strong>{money(quote.total)}</strong></p><Link className="shopping-primary" href="/checkout">Continue to checkout</Link></>:<p>{busy?"Updating totals…":"Checking current prices and stock…"}</p>}<p>Adding to cart does not reserve stock. Stock is checked again at checkout.</p><Link href="/checkout">View existing pending checkout</Link></aside></div>}</main>;
}
