"use client";
import Link from "next/link";
import {useEffect,useRef,useState} from "react";
import {adminRequest} from "../../lib/admin-api";
import {CartItem,Quote,PendingOrder,readCart,checkoutItems} from "../../lib/cart";
import {money} from "../../lib/product";
const ORDER_KEY="styled-somehow-pending-order";
export default function CheckoutView(){
 const [items,setItems]=useState<CartItem[]>([]),[quote,setQuote]=useState<Quote|null>(null),[order,setOrder]=useState<PendingOrder|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(""),[now,setNow]=useState(0);
 const pending=useRef<{signature:string;id:string}|null>(null);
 async function getQuote(cart:CartItem[]){return adminRequest<Quote>("/api/cart/quote",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({items:checkoutItems(cart)})});}
 useEffect(()=>{let live=true;async function load(){const cart=readCart();if(live)setItems(cart);const id=localStorage.getItem(ORDER_KEY);if(id){try{const saved=await adminRequest<PendingOrder>(`/api/checkout/${encodeURIComponent(id)}`);if(live){setOrder(saved);setNow(Date.now());}return;}catch(e){if(live)setError(e instanceof Error?e.message:"Cannot load pending order");}}
 if(cart.length){try{const q=await getQuote(cart);if(live)setQuote(q);}catch(e){if(live)setError(e instanceof Error?e.message:"Could not validate checkout");}}}
 void load().catch(()=>{if(live)setError("Cannot load checkout in this browser.");}).finally(()=>{if(live)setLoading(false);});return()=>{live=false;};},[]);
 useEffect(()=>{if(!order||order.status!=="PENDING_PAYMENT")return;let live=true;const timer=setInterval(()=>{setNow(Date.now());if(Date.now()>=Date.parse(order.expiresAt)&&Math.floor(Date.now()/1000)%10===0)adminRequest<PendingOrder>(`/api/checkout/${order.id}`).then(o=>{if(live)setOrder(o);}).catch(()=>{if(live)setError("Cannot confirm reservation status. Please refresh.");});},1000);return()=>{live=false;clearInterval(timer);};},[order]);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!quote||busy)return;const form=new FormData(e.currentTarget);const address=Object.fromEntries(["name","email","phone","line1","line2","city","state","pinCode"].map(key=>[key,String(form.get(key)||"").trim()]));const data={items:checkoutItems(items),address,expectedTotal:quote.total};const signature=JSON.stringify(data);if(pending.current?.signature!==signature)pending.current={signature,id:crypto.randomUUID()};setBusy(true);setError("");try{const saved=await adminRequest<PendingOrder>("/api/checkout",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...data,requestId:pending.current.id})});setOrder(saved);setNow(Date.now());try{localStorage.setItem(ORDER_KEY,saved.id);}catch{setError("Pending checkout created, but this browser could not save its reference. Keep this page open.");}}catch(e){setError(e instanceof Error?e.message:"Checkout failed");}finally{setBusy(false);}}
 async function cancel(){if(!order)return;setBusy(true);setError("");try{const cancelled=await adminRequest<PendingOrder>(`/api/checkout/${order.id}/cancel`,{method:"POST"});setOrder(cancelled);}catch(e){setError(e instanceof Error?e.message:"Could not cancel");}finally{setBusy(false);}}
 async function startAgain(){setBusy(true);setError("");try{localStorage.removeItem(ORDER_KEY);pending.current=null;const cart=readCart();setItems(cart);setOrder(null);setQuote(cart.length?await getQuote(cart):null);}catch(e){setError(e instanceof Error?e.message:"Cannot restart checkout");}finally{setBusy(false);}}
 const seconds=order?Math.max(0,Math.ceil((Date.parse(order.expiresAt)-now)/1000)):0;
 return <main className="shopping-page"><nav className="product-nav"><Link className="brand-logo" href="/" aria-label="Styled Somehow home"><span>STYLED</span><span>SOMEHOW</span></Link><Link href="/cart">← Back to cart</Link></nav><h1>Guest checkout</h1>{error&&<p className="shopping-error" role="alert">{error}</p>}
 {loading?<p>Loading checkout…</p>:order?<section className="checkout-summary"><h2>{order.status==="PENDING_PAYMENT"?"Pending checkout — payment not received":order.status==="EXPIRED"?"Reservation expired":"Checkout cancelled"}</h2><p>Reference: {order.id}</p><p>Status: {order.status}</p>{order.items.map((i,j)=><p key={j}>{i.name} · {i.colour} · {i.size} × {i.quantity} <strong>{money(i.unitPrice*i.quantity)}</strong></p>)}<p>Shipping <strong>Free · ₹0</strong></p><p>Total <strong>{money(order.total)}</strong></p><p>Deliver to {order.name}, {order.line1}, {order.city}, {order.state} {order.pinCode}</p>{order.status==="PENDING_PAYMENT"?<><p>Stock reserved for {Math.floor(seconds/60)}:{String(seconds%60).padStart(2,"0")}. This is not a paid or confirmed purchase.</p><p>Online payment is not available yet. No payment has been taken and this checkout will not be dispatched.</p><button disabled={busy} onClick={cancel}>Cancel checkout and release stock</button></>:<button disabled={busy} onClick={startAgain}>Start checkout again</button>}</section>:!items.length?<p>Your cart is empty. <Link href="/#new-in">Shop the collection</Link>.</p>:<div className="shopping-layout"><form onSubmit={submit} className="checkout-form"><h2>Delivery details · India</h2><fieldset disabled={busy||!quote}><label>Full name<input name="name" required maxLength={100} autoComplete="name"/></label><label>Email<input name="email" type="email" required maxLength={180} autoComplete="email"/></label><label>Mobile number<input name="phone" type="tel" required pattern="[6-9][0-9]{9}" maxLength={10} inputMode="numeric" placeholder="10-digit mobile number" autoComplete="tel-national"/></label><label>Address<input name="line1" required maxLength={200} autoComplete="address-line1"/></label><label>Apartment / landmark (optional)<input name="line2" maxLength={200} autoComplete="address-line2"/></label><label>City<input name="city" required maxLength={100} autoComplete="address-level2"/></label><label>State<input name="state" required maxLength={100} autoComplete="address-level1"/></label><label>PIN code<input name="pinCode" required pattern="[1-9][0-9]{5}" maxLength={6} inputMode="numeric" autoComplete="postal-code"/></label><button className="shopping-primary" disabled={!quote||busy}>{busy?"Creating checkout…":"Create pending checkout"}</button></fieldset></form><aside className="checkout-summary"><h2>Order summary</h2>{quote?<>{quote.items.map((i,j)=><p key={j}>{i.name} · {i.colour} · {i.size} × {i.quantity}<strong>{money(i.unitPrice*i.quantity)}</strong></p>)}<p>Shipping<strong>Free · ₹0</strong></p><p>Total<strong>{money(quote.total)}</strong></p></>:<p>Return to your cart to review prices and stock.</p>}<p>Online payment is currently unavailable. This checkout reserves stock for 15 minutes; no payment is taken.</p><p>Delivery availability will be confirmed before payment becomes available.</p></aside></div>}</main>;
}
