package com.styledsomehow.backend;
import com.styledsomehow.backend.checkout.*;
import com.styledsomehow.backend.inventory.*;
import com.styledsomehow.backend.payments.*;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.bean.override.mockito.MockitoBean;
import org.springframework.transaction.annotation.Transactional;
import java.util.*;
import java.time.Instant;
import static com.styledsomehow.backend.checkout.CheckoutDtos.*;
import static org.assertj.core.api.Assertions.*;
import static org.mockito.Mockito.*;
@SpringBootTest @Transactional @org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc
class PaymentIntegrationTests {
 @Autowired CheckoutService checkout;@Autowired PaymentService payments;@Autowired StockRepository stocks;@Autowired OrderRepository orders;@Autowired PaymentRepository receipts;
 @MockitoBean PaymentGateway gateway;
 @Autowired org.springframework.test.web.servlet.MockMvc mvc;
 @BeforeEach void setup(){when(gateway.ready()).thenReturn(true);when(gateway.keyId()).thenReturn("rzp_test_fixture");when(gateway.createOrFindOrder(anyString(),anyLong())).thenAnswer(i->new PaymentGateway.GatewayOrder("order_"+i.getArgument(0,String.class).replace("-",""),i.getArgument(1,Long.class),"INR",i.getArgument(0)));when(gateway.verifyCheckout(anyString(),anyString(),anyString())).thenReturn(true);}
 PendingOrder order(String owner){var address=new Address("Fixture","fixture@gmail.com","9999999999","Test address","","Ahmedabad","Gujarat","380054");var o=checkout.create(new Checkout(List.of(new Item("cherry-zest-oversized-t-shirt","White","S",2)),address(),UUID.randomUUID().toString(),1198),owner);payments.start(o.id,owner);return o;}
 BlankStock stock(){return stocks.findAll().stream().filter(s->s.colour.equals("White")&&s.size.equals("S")).findFirst().orElseThrow();}
 void capture(PendingOrder o,String id){when(gateway.fetchPayment(id)).thenReturn(new PaymentGateway.Payment(id,o.gatewayOrderId,119800,"INR","captured",0));payments.verify(o.id,o.sessionKey,id,"signature");}
 @Test void capturedPaymentConsumesOnlyOnce(){var o=order("owner");capture(o,"pay_once");capture(o,"pay_once");assertThat(o.status).isEqualTo("PAID");assertThat(stock().quantity).isEqualTo(10);assertThat(stock().reserved).isZero();assertThat(receipts.findById("pay_once").orElseThrow().status).isEqualTo("PAID");}
 @Test void authorizedIsNotPaidAndInvalidSignatureDoesNotFetch(){var o=order("owner");when(gateway.fetchPayment("pay_auth")).thenReturn(new PaymentGateway.Payment("pay_auth",o.gatewayOrderId,119800,"INR","authorized",0));payments.verify(o.id,"owner","pay_auth","signature");assertThat(o.status).isEqualTo("PENDING_PAYMENT");assertThat(stock().quantity).isEqualTo(12);when(gateway.verifyCheckout(anyString(),eq("pay_bad"),anyString())).thenReturn(false);assertThatThrownBy(()->payments.verify(o.id,"owner","pay_bad","invalid")).isInstanceOf(org.springframework.web.server.ResponseStatusException.class);verify(gateway,never()).fetchPayment("pay_bad");}
 @Test void rejectsOtherBrowserAndForeignPayment(){var o=order("owner");assertThatThrownBy(()->payments.start(o.id,"other")).isInstanceOf(org.springframework.web.server.ResponseStatusException.class);when(gateway.fetchPayment("pay_foreign")).thenReturn(new PaymentGateway.Payment("pay_foreign","order_other",119800,"INR","captured",0));assertThatThrownBy(()->payments.verify(o.id,"owner","pay_foreign","signature")).isInstanceOf(org.springframework.web.server.ResponseStatusException.class);assertThat(stock().quantity).isEqualTo(12);}
 @Test void reusedPaymentOrderUsesServerTotal(){var o=order("owner");assertThat(payments.start(o.id,"owner").amount()).isEqualTo(119800);verify(gateway,times(1)).createOrFindOrder(o.id,119800);}
 @Test void latePaymentCanUseAvailableStock(){var o=order("owner");o.expiresAt=Instant.now().minusSeconds(1);orders.saveAndFlush(o);capture(o,"pay_late");assertThat(o.status).isEqualTo("PAID");assertThat(stock().quantity).isEqualTo(10);assertThat(stock().reserved).isZero();}
 @Test void unavailableLatePaymentQueuesRefundAndRetriesSameKey(){var o=order("owner");o.expiresAt=Instant.now().minusSeconds(1);orders.saveAndFlush(o);checkout.expireReservations();stock().quantity=1;stocks.flush();capture(o,"pay_unavailable");assertThat(o.status).isEqualTo("REFUND_PENDING");assertThat(stock().quantity).isEqualTo(1);var r=receipts.findById("pay_unavailable").orElseThrow();when(gateway.refund(r.id,r.amount,r.refundKey)).thenThrow(new IllegalStateException("fixture timeout")).thenReturn(new PaymentGateway.Refund("rfnd_done","processed"));payments.reconcileRefund(r.id);assertThat(r.retries).isEqualTo(1);payments.reconcileRefund(r.id);assertThat(r.status).isEqualTo("REFUNDED");assertThat(o.status).isEqualTo("REFUNDED");verify(gateway,times(2)).refund(r.id,119800,r.refundKey);}
 @Test void cancelledAndExtraPaymentsAreRefunded(){var o=order("owner");checkout.cancel(o.id,"owner");capture(o,"pay_cancelled");assertThat(o.status).isEqualTo("REFUND_PENDING");assertThat(stock().quantity).isEqualTo(12);var paid=order("second");capture(paid,"pay_original");capture(paid,"pay_extra");assertThat(paid.status).isEqualTo("PAID");assertThat(paid.paymentId).isEqualTo("pay_original");assertThat(stock().quantity).isEqualTo(10);assertThat(receipts.findById("pay_extra").orElseThrow().status).isEqualTo("REFUND_PENDING");}
 @Test void mismatchRequiresReviewAndReleasesReservation(){var o=order("owner");when(gateway.fetchPayment("pay_wrong")).thenReturn(new PaymentGateway.Payment("pay_wrong",o.gatewayOrderId,100,"INR","captured",0));payments.verify(o.id,"owner","pay_wrong","signature");assertThat(o.status).isEqualTo("PAYMENT_REVIEW");assertThat(stock().quantity).isEqualTo(12);assertThat(stock().reserved).isZero();}
 @Test void webhookRequiresSignatureAndDuplicateDeliveryIsSafe() throws Exception{var o=order("owner");when(gateway.fetchPayment("pay_hook")).thenReturn(new PaymentGateway.Payment("pay_hook",o.gatewayOrderId,119800,"INR","captured",0));String body="{\"event\":\"payment.captured\",\"payload\":{\"payment\":{\"entity\":{\"id\":\"pay_hook\"}}}}";mvc.perform(org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post("/api/payments/razorpay/webhook").contentType("application/json").content(body)).andExpect(org.springframework.test.web.servlet.result.MockMvcResultMatchers.status().isBadRequest());verify(gateway,never()).fetchPayment("pay_hook");when(gateway.verifyWebhook(any(byte[].class),eq("fixture-signature"))).thenReturn(true);for(int i=0;i<2;i++)mvc.perform(org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post("/api/payments/razorpay/webhook").header("X-Razorpay-Signature","fixture-signature").contentType("application/json").content(body)).andExpect(org.springframework.test.web.servlet.result.MockMvcResultMatchers.status().isNoContent());assertThat(stock().quantity).isEqualTo(10);mvc.perform(org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post("/api/checkout/"+o.id+"/payment")).andExpect(org.springframework.test.web.servlet.result.MockMvcResultMatchers.status().isForbidden());}
 @Test void signaturesUseExactBytesAndLiveKeysAreDisabled() throws Exception{var body="order_fixture|pay_fixture".getBytes(java.nio.charset.StandardCharsets.UTF_8);var mac=javax.crypto.Mac.getInstance("HmacSHA256");mac.init(new javax.crypto.spec.SecretKeySpec("fixture-secret".getBytes(),"HmacSHA256"));var signature=HexFormat.of().formatHex(mac.doFinal(body));assertThat(RazorpayGateway.validSignature(body,signature,"fixture-secret")).isTrue();assertThat(RazorpayGateway.validSignature("changed".getBytes(),signature,"fixture-secret")).isFalse();assertThat(RazorpayGateway.validSignature(body,null,"fixture-secret")).isFalse();assertThat(new RazorpayGateway("rzp_live_fixture","secret","a".repeat(32)).ready()).isFalse();}
}
