"use client";
import Link from "next/link";
import {useState} from "react";
import {adminRequest} from "../../lib/admin-api";
import {PendingOrder} from "../../lib/cart";
import {GMAIL_PATTERN,GMAIL_HINT,isGmail} from "../../lib/email";
import {money} from "../../lib/product";
export default function OrderAccessView(){
 const [challenge,setChallenge]=useState(""),[message,setMessage]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[order,setOrder]=useState<PendingOrder|null>(null);
 const [reference,setReference]=useState(""),[email,setEmail]=useState(""),[code,setCode]=useState("");
 async function request(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!isGmail(email)){setError(GMAIL_HINT);return;}setBusy(true);setError("");setMessage("");try{const result=await adminRequest<{challengeId:string;message:string}>("/api/order-access/request",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({orderId:reference.trim(),email:email.trim()})});setChallenge(result.challengeId);setCode("");setMessage(result.message);}catch(e){setError(e instanceof Error?e.message:"Could not request a code");}finally{setBusy(false);}}
 async function verify(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");try{const result=await adminRequest<{orderId:string}>("/api/order-access/verify",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({challengeId:challenge,code})});const found=await adminRequest<PendingOrder>(`/api/order-access/order/${encodeURIComponent(result.orderId)}`);setOrder(found);setMessage("");}catch(e){setError(e instanceof Error?e.message:"Invalid or expired code");}finally{setBusy(false);}}
 async function close(){setBusy(true);setError("");try{await adminRequest<void>("/api/order-access/close",{method:"POST"});setOrder(null);setChallenge("");setCode("");}catch(e){setError(e instanceof Error?e.message:"Could not close order access");}finally{setBusy(false);}}
 return <main className="shopping-page"><nav className="product-nav"><Link className="brand-logo" href="/" aria-label="Styled Somehow home"><span>STYLED</span><span>SOMEHOW</span></Link><Link href="/cart">Cart</Link></nav><h1>View your order</h1><p>No account needed. Use your order reference and the email entered at checkout.</p>{error&&<p role="alert" className="shopping-error">{error}</p>}{message&&<p role="status">{message}</p>}
 {order?<section className="checkout-summary"><h2>{order.status.replaceAll("_"," ")}</h2><p>Reference: {order.id}</p>{order.items.map((i,j)=><p key={j}>{i.name} · {i.colour} · {i.size} × {i.quantity}<strong>{money(i.unitPrice*i.quantity)}</strong></p>)}<p>Shipping<strong>Free · ₹0</strong></p><p>Total<strong>{money(order.total)}</strong></p><p>Delivery address: {order.name}, {order.line1}{order.line2?`, ${order.line2}`:""}, {order.city}, {order.state} {order.pinCode}</p>{order.status==="PENDING_PAYMENT"&&<p>Payment has not been received. This is not a confirmed purchase.</p>}<p>Courier tracking will appear here once shipping integration is available.</p><button disabled={busy} onClick={close}>Close order access</button></section>:<section className="checkout-form">{!challenge?<form onSubmit={request}><fieldset disabled={busy}><label>Order reference<input required maxLength={36} minLength={36} value={reference} onChange={e=>setReference(e.target.value)} autoComplete="off"/></label><label>Checkout email<input required type="email" pattern={GMAIL_PATTERN} title={GMAIL_HINT} aria-describedby="order-email-hint" maxLength={180} value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email"/><small id="order-email-hint">{GMAIL_HINT}</small></label><button className="shopping-primary">{busy?"Requesting…":"Email me a code"}</button></fieldset></form>:<form onSubmit={verify}><fieldset disabled={busy}><label>6-digit code<input required pattern="[0-9]{6}" maxLength={6} inputMode="numeric" autoComplete="one-time-code" value={code} onChange={e=>setCode(e.target.value)}/></label><p>Maximum 5 code requests per Gmail address in 24 hours. Exceeding this triggers a 3-hour block.</p><p>Codes expire in 10 minutes. You can try up to five times.</p><button className="shopping-primary">{busy?"Checking…":"Verify and view order"}</button><button type="button" onClick={()=>{setChallenge("");setCode("");setMessage("");setError("");}}>Change details or request another code</button></fieldset></form>}<p>On a shared device, close order access when finished. Access expires after 30 minutes.</p></section>}</main>;
}
